# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chaitanya Ahuja
email: mail@chahuja.com
address: >-
  Gates Hillman Center, 5719 <br>
  Carnegie Mellon University
description: .
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chahuja.com" # the base hostname & protocol for your site, e.g. http://example.com

google_scholar: https://scholar.google.com/citations?hl=en&user=CX8zqPoAAAAJ
github_username:  chahuja
google_analytics: UA-59835835-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
timezone: America/New_York

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bibble/
  - README.md
